; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30147.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG115556 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
$SG117096 DB	'%s', 00H
	ORG $+9
$SG115557 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG115558 DB	'qRegisterNormalizedMetaType', 00H
$SG117099 DB	00H, 00H
	ORG $+2
?qt_meta_data_QtGuiqq@@3QBIB DD 08H			; qt_meta_data_QtGuiqq
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	ORG $+4
$SG115908 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG115909 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG115910 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG116260 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG116261 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG116262 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG117095 DB	'invalid argument', 00H
	ORG $+7
$SG117097 DB	'D:\vs\VC\Tools\MSVC\14.29.30133\include\xmemory', 00H
	ORG $+8
$SG117098 DB	'D', 00H, ':', 00H, '\', 00H, 'v', 00H, 's', 00H, '\', 00H
	DB	'V', 00H, 'C', 00H, '\', 00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l'
	DB	00H, 's', 00H, '\', 00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H
	DB	'\', 00H, '1', 00H, '4', 00H, '.', 00H, '2', 00H, '9', 00H, '.'
	DB	00H, '3', 00H, '0', 00H, '1', 00H, '3', 00H, '3', 00H, '\', 00H
	DB	'i', 00H, 'n', 00H, 'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e'
	DB	00H, '\', 00H, 'x', 00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H
	DB	'r', 00H, 'y', 00H, 00H, 00H
$SG117100 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG113002 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+4
$SG113003 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG113004 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@QtGuiqq@@UEBAPEBUQMetaObject@@XZ	; QtGuiqq::metaObject
PUBLIC	?qt_metacast@QtGuiqq@@UEAAPEAXPEBD@Z		; QtGuiqq::qt_metacast
PUBLIC	?qt_metacall@QtGuiqq@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; QtGuiqq::qt_metacall
PUBLIC	?qt_static_metacall@QtGuiqq@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QtGuiqq::qt_static_metacall
PUBLIC	?staticMetaObject@QtGuiqq@@2UQMetaObject@@B	; QtGuiqq::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@QtGuiqq@@2UQMetaObject@@B DB 030H DUP (?) ; QtGuiqq::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@QtGuiqq@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@QtGuiqq@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@QtGuiqq@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@QtGuiqq@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@QtGuiqq@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$?qt_metacall@QtGuiqq@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@QtGuiqq@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@QtGuiqq@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@QtGuiqq@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
_DATA	SEGMENT
?qt_meta_stringdata_QtGuiqq@@3Uqt_meta_stringdata_QtGuiqq_t@@B DD 0ffffffffH ; qt_meta_stringdata_QtGuiqq
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	051H
	DB	074H
	DB	047H
	DB	075H
	DB	069H
	DB	071H
	DB	071H
	DB	00H
_DATA	ENDS
xdata	SEGMENT
$unwind$?metaObject@QtGuiqq@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@QtGuiqq@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@QtGuiqq@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@QtGuiqq@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@QtGuiqq@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'QtGuiqq::staticMetaObject'', COMDAT
; File D:\QTQQ\qq\QtGuiqq\x64\Debug\moc\moc_QtGuiqq.cpp
; Line 66
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@QtGuiqq@@2UQMetaObject@@B, rax
; Line 67
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_QtGuiqq@@3Uqt_meta_stringdata_QtGuiqq_t@@B
	mov	QWORD PTR ?staticMetaObject@QtGuiqq@@2UQMetaObject@@B+8, rax
; Line 68
	lea	rax, OFFSET FLAT:?qt_meta_data_QtGuiqq@@3QBIB
	mov	QWORD PTR ?staticMetaObject@QtGuiqq@@2UQMetaObject@@B+16, rax
; Line 69
	lea	rax, OFFSET FLAT:?qt_static_metacall@QtGuiqq@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QtGuiqq::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@QtGuiqq@@2UQMetaObject@@B+24, rax
; Line 70
	mov	QWORD PTR ?staticMetaObject@QtGuiqq@@2UQMetaObject@@B+32, 0
; Line 71
	mov	QWORD PTR ?staticMetaObject@QtGuiqq@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@QtGuiqq@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'QtGuiqq::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@QtGuiqq@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; QtGuiqq::qt_static_metacall
; File D:\QTQQ\qq\QtGuiqq\x64\Debug\moc\moc_QtGuiqq.cpp
; Line 58
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 63
	ret	0
?qt_static_metacall@QtGuiqq@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QtGuiqq::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@QtGuiqq@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; QtGuiqq::qt_metacall
; File D:\QTQQ\qq\QtGuiqq\x64\Debug\moc\moc_QtGuiqq.cpp
; Line 89
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 90
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 91
	mov	eax, DWORD PTR _id$[rsp]
; Line 92
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@QtGuiqq@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QtGuiqq::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@QtGuiqq@@UEAAPEAXPEBD@Z PROC		; QtGuiqq::qt_metacast
; File D:\QTQQ\qq\QtGuiqq\x64\Debug\moc\moc_QtGuiqq.cpp
; Line 81
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 82
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 83
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_QtGuiqq@@3Uqt_meta_stringdata_QtGuiqq_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 84
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 85
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 86
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@QtGuiqq@@UEAAPEAXPEBD@Z ENDP		; QtGuiqq::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@QtGuiqq@@UEBAPEBUQMetaObject@@XZ PROC	; QtGuiqq::metaObject
; File D:\QTQQ\qq\QtGuiqq\x64\Debug\moc\moc_QtGuiqq.cpp
; Line 76
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 77
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@QtGuiqq@@2UQMetaObject@@B ; QtGuiqq::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 78
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@QtGuiqq@@UEBAPEBUQMetaObject@@XZ ENDP	; QtGuiqq::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.12.3\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
